// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvUNJzHnZfA9r2ew7AGty9mgSpVjDPj4c',
    appId: '1:618475193124:web:8b1db7fd7e76f89f77a9b1',
    messagingSenderId: '618475193124',
    projectId: 'doctor-hunt-67c1b',
    authDomain: 'doctor-hunt-67c1b.firebaseapp.com',
    storageBucket: 'doctor-hunt-67c1b.firebasestorage.app',
    measurementId: 'G-VHRJ0FBPCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZyG1_asYxlfri14SzKcDn7ltevTFDnWc',
    appId: '1:618475193124:android:c273a037aacb927577a9b1',
    messagingSenderId: '618475193124',
    projectId: 'doctor-hunt-67c1b',
    storageBucket: 'doctor-hunt-67c1b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvUNJzHnZfA9r2ew7AGty9mgSpVjDPj4c',
    appId: '1:618475193124:web:371d9373f9e54d4777a9b1',
    messagingSenderId: '618475193124',
    projectId: 'doctor-hunt-67c1b',
    authDomain: 'doctor-hunt-67c1b.firebaseapp.com',
    storageBucket: 'doctor-hunt-67c1b.firebasestorage.app',
    measurementId: 'G-M1204M1EZG',
  );
}
